import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    success: true,
    models: [
      {
        id: 'gpt-4o-mini',
        name: 'OpenAI GPT-4o-mini',
        description: "OpenAI's fastest compact model",
        isPro: false,
        isNew: false,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'gemini-2.5-flash',
        name: 'Google Gemini 2.5 Flash',
        description: "Google's latest reasoning model",
        isPro: false,
        isNew: true,
        isPreview: false,
        icon: 'google',
        provider: 'google',
      },
      {
        id: 'grok-3-mini',
        name: 'Grok 3 Mini',
        description: "X AI's advanced reasoning model",
        isPro: false,
        isNew: true,
        isPreview: false,
        icon: 'x-ai',
        provider: 'x-ai',
      },
      {
        id: 'gpt-4.1-nano',
        name: 'OpenAI GPT-4.1-nano',
        description: "OpenAI's fastest compact model",
        isPro: false,
        isNew: true,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'o4-mini',
        name: 'OpenAI o4-mini',
        description: "OpenAI's efficient reasoning model",
        isPro: false,
        isNew: true,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'claude-4-sonnet',
        name: 'Anthropic Claude 4 Sonnet',
        description: "Anthropic's best coding model",
        isPro: true,
        isNew: true,
        isPreview: false,
        icon: 'anthropic',
        provider: 'anthropic',
      },
      {
        id: 'gpt-4.1',
        name: 'OpenAI GPT-4.1',
        description: "OpenAI's most advanced model",
        isPro: true,
        isNew: true,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'o4-mini-high',
        name: 'OpenAI o4-mini (High)',
        description: "OpenAI's best reasoning model",
        isPro: true,
        isNew: true,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'gpt-4o',
        name: 'OpenAI GPT-4o',
        description: "OpenAI's most advanced model",
        isPro: true,
        isNew: false,
        isPreview: false,
        icon: 'openai',
        provider: 'openai',
      },
      {
        id: 'deepseek-r1',
        name: 'Deepseek R1',
        description: 'Optimized for reasoning tasks',
        isPro: true,
        isNew: false,
        isPreview: true,
        icon: 'deepseek',
        provider: 'deepseek',
      },
      {
        id: 'claude-3.7-sonnet',
        name: 'Anthropic Claude 3.7 Sonnet',
        description: "Anthropic's most advanced model",
        isPro: true,
        isNew: false,
        isPreview: false,
        icon: 'anthropic',
        provider: 'anthropic',
      },
    ],
  });
}
